# Generated by Django 3.2.8 on 2022-06-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnail', '0002_thumbnail_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='image_thumbnail',
        ),
    ]
